version: "3"
services:
  mongo:
    image: mongo:3.4.23
    ports:
      - "27017:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.0
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/:rw
      - ./logstash/logstash.conf/:/usr/share/logstash/logstash.conf/:rw
    depends_on:
      - elasticsearch
    ports:
      - "5514:5514/udp"
    command: "logstash -f ./logstash.conf"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    environment:
      ELASTICSEARCH_URL: http://localhost:9200
    ports:
      - "5601:5601"

  simple_jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
