on: [push, pull_request]
name: go-unit-test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run mongdb
        uses: wbari/start-mongoDB@v0.2
      - name: Unit Test & Integration Test
        run: go test ./... -tags integration
        env:
          MONGODB_ENDPOINT: "mongodb://localhost:27017"
          MONGODB_COMPANY_TABLE_NAME: "company_test"
          MONGODB_STAFF_TABLE_NAME: "staff_test"
          MONGODB_NAME: "go_project"
          APP_NAME: "gogo_blueprint"
          JAEGER_ENDPOINT: "http://localhost:9411/api/v1/spans"
          LOGSTASH_ENDPOINT: "localhost:5514"
          JAEGER_AGENT_HOST: localhost
          JAEGER_AGENT_PORT: 6831
