on: [push, pull_request]
name: go-unit-test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run mongdb
        uses: wbari/start-mongoDB@v0.2
      - name: Test
        run: source ./development/local.env && go test ./... -tags integration
